const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_SYSTEM_LANGUAGE: "CHANGE_SYSTEM_LANGUAGE",
  //admin
  // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
  // PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  FETCH_TOP_DOCTORS_HOME_START: "FETCH_TOP_DOCTORS_HOME_START",
  FETCH_TOP_DOCTORS_HOME_SUCCESS: "FETCH_TOP_DOCTORS_HOME_SUCCESS",
  FETCH_TOP_DOCTORS_HOME_FAIL: "FETCH_TOP_DOCTORS_HOME_FAIL",

  FETCH_ALL_DOCTORS_START: "FETCH_ALL_DOCTORS_START",
  FETCH_ALL_DOCTORS_SUCCESS: "FETCH_ALL_DOCTORS_SUCCESS",
  FETCH_ALL_DOCTORS_FAIL: "FETCH_ALL_DOCTORS_FAIL",

  // admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",
  FETCH_POSITION_START: "FETCH_POSITION_START",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIL: "FETCH_POSITION_FAIL",
  FETCH_ROLE_START: "FETCH_ROLE_START",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAIL: "FETCH_ALL_USER_FAIL",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  //manage doctor
  SAVE_DOCTOR_INFO_SUCCESS: "SAVE_DOCTOR_INFO_SUCCESS",
  SAVE_DOCTOR_INFO_FAIL: "SAVE_DOCTOR_INFO_FAIL",

  FETCH_ALLCODE_SCHEDULE_SUCCESS: "FETCH_ALLCODE_SCHEDULE_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_FAIL: "FETCH_ALLCODE_SCHEDULE_FAIL",

  FETCH_REQUIRE_DOCTOR_INFO_SUCCESS: "FETCH_REQUIRE_DOCTOR_INFO_SUCCESS",
  FETCH_REQUIRE_DOCTOR_INFO_FAIL: "FETCH_ALLCODE_SCHEDULE_FAIL",
});

export default actionTypes;
